DeviationTX/deviation

src/protocol/h8_3d_nrf24l01.c

Add extra channels to H8_3D protocol for JJRC H11D:
- Channel 7: camera snapshot
- Channel 8: video recording
- Channel 11 (3 positions): camera gimball down / up
Tested successfully by wasp09:
http://www.deviationtx.com/forum/protocol-development/4724-jjrc-h20-hex-quad?start=140#49519

Add extra channels for JJRC H11D

---

src/protocol/h8_3d_nrf24l01.c

Fix rf channel hopping for H8_3D protocol and add extra flags for JJRC H11D

Fix rf channel hopping for H8_3D protocol and add extra flags for JJRC H11D

---

src/protocol/cflie_nrf24l01.c

Original commit message from tobbeanton:
Ajusted thrust to work with Crazyflie 2.0 thrust-lock. Changed + to x mode rotation to be optional to have Crazyflie 2.0 in X mode.

Merging a change to enable Crazyflie 2.0 from the defunct bitbucket repo into the github repo

---

src/protocol/mt99xx_nrf24l01.c

Channels for Invert, Video and Snapshot which are available on the LS215.

Added more channels for LS

---

src/protocol/hubsan_a7105.c

Add H301 format to Hubsan protocol.
- Channel 5: LEDs
- Channel 6: stabilized / manual flight modes
- Channel 8: video record
- Channel 10: Return to Home
Forums thread: http://www.deviationtx.com/forum/protocol-development/5028-the-new-hubsans

Add H301 format

---

src/protocol/mjxq_nrf24l01.c

- disable dynamic trims while in headless mode
- fix bind issue with some transmitter ID

Protocol e010 fixes

---

src/protocol/hontai_nrf24l01.c

Add FQ777-951 format to Hontai protocol  
- channel 6: flip
- channel 7: snapshot (FQ777-951C)
- channel 8: video (FQ777-951C)
- channel 9: headless

Add FQ777-951 format to Hontai protocol

---

src/protocol/frsky1way_cc2500.c

ID is on 15 bits only not 16 bits.
The protocol is now supporting 8 channels and not only 4 has before.

FrSky 1 way: Fixed ID and 8 channels

---

src/protocol/fq777_nrf24l01.c

Removed redefinition of BIND_COUNT

Removed redefinition of BIND_COUNT at fq777 protocol

---

src/protocol/yd717_nrf24l01.c

After swapping out the nrf24l01 in my 7e for the 4-in-1 module, I could no longer fly the Syma X7 without a huge amount of lag.
Some investigation later, and it turns out that Auto-Ack was the culprit, with the 4-in-1 not receiving the ACKs and wasting lots of time on re-transmits. 
A fast fix was to allow the user to selectively disable AA.
More details:
http://www.deviationtx.com/forum/6-general-discussions/6230-my-devo-7e-4-in1-2x3-build-and-syma-x4-issues

Adding a user option to disable Auto-Acknowledge on the YD717 Protocol's

---

src/pages/320x240x16/guiobj.h
src/pages/320x240x16/scanner_page.c
src/pages/320x240x16/scanner_page.h

Changed the scanning algorithm. Now you can see even jumping FHSS channels. Added the attenuator option (0dB or -20dB) for strong/near RF sources.

RF Scanner improvement

---

src/protocol/v202_nrf24l01.c

Add JXD-506 format option to V202 protocol
Channel mapping:
Same than standard V202 except for channels 10-12
- Channel 10: start / stop engines
- Channel 11: emergency stop
- Channel 12: gimbal control
Throttle stick needs to be centered before the quad can be armed.
I also modified the documentation.
Compatibility tested with JXD-506, JJRC H28WH and Yizhan i8h
http://www.deviationtx.com/forum/protocol-development/6440-jxd-506-potentially-jjrc-h28wh

Add JXD-506 format option to V202 protocol

---

src/protocol/dsm2_cyrf6936.c
src/protocol/j6pro_cyrf6936.c
src/telemetry/telem_dsm.c

Fixed all errors that I can find. Changed the sensor names to be shorter (no more than 7 symbols) and more recognizable. Now "Telemetry config" page work fine for all telemetry sensors.

 DSM telemetry update #2 

---

src/protocol/devo_cyrf6936.c

Nothing new, added comments for CYRF programming and code clean up.

DEVO protocol update

---

src/protocol/cflie_nrf24l01.c

This makes use of the crazyflie logging framework and uses the DSM telemetry type on deviationtx

Implementation of telemetry support for the cflie protocol

---

src/telemetry.c

Fix telemetry items loading for CFlie and AFHDS 2A protocols

Fix telemetry items loading for CFlie and AFHDS 2A protocols

---

src/protocol/assan_nrf24l01.c

Fix ASSAN transmitter ID
Fix bind with some ASSAN receivers:
https://www.deviationtx.com/forum/protocol-development/2038-what-about-assan?start=80#57674
After this patch, ASSAN receivers will need to rebind, sorry for that ...

Fix ASSAN transmitter ID

---

src/target/devof4/Makefile.inc
src/target/devof4/channels.c

Use separate channels.c for Devo F4 & F7, fix broken nightly build after this pull request:
https://github.com/DeviationTX/deviation/pull/95

Use separate channels.c for Devo F4 & F7

---

src/protocol/frskyx_cc2500.c

This change adds a FrskyX protocol option for EU firmware compatibility. Select Format protocol option to EU to work with EU receiver firmware. Set option to FCC for standard firmware.
Thanks to midelic and Mike for the implementation from the DIY multiprotocol project.

FrskyX EU firmware support, from hexfet

---

src/pages/common/_model_loadsave.c
src/pages/common/model_page.h

Reverts DeviationTX/deviation#135

Revert "Increase maximum number of model files from 100 to 255, from hexfet"

---

src/target/devof12e/lcd_page_props.h

Minimal item size for Devo F12E is 2.

Fix "HEADER_WIDGET_HEIGHT" for Devo F12E

---

src/pages/128x64x1/standard/drexp_page.c

D/R can't be greater 100%, above 101% transmitter freeze and reboot.

Fix "text" GUI "Standard" - DR can't be greater 100%

---

src/pages/128x64x1/lang_select.c
src/pages/text/lang_select.c

Fix language select page for "text" GUI

---

src/fs/text/media/config.ini

The last 128x64x1 main screen changes destroy Devo F7 main screen.

Fix Devo F7 main screen

---

src/pages/text/toggle_select.c
src/target/devof12e/lcd.c
src/target/devof12e/tw8816.c
src/target/devof12e/tw8816_map.c
src/target/emu_devof12e/lcd.c

The fix create basis for language support for languages based on Latin charset.

Fix Latin supplement symbols for Devo F12E

---

src/pages/common/_debuglog_page.c

1. Fix Windows built emulator crash at debuglog page
2. Fix debuglog circularity at debuglog page. Debuglog entries repeated 2, 3, 4... times at debuglog screen, depending from length of entries.

Fix debuglog page

---

src/gui/xygraph.c

GUI_DrawXYGraph() has miscalculation for point and axis position.

Fix GUI_DrawXYGraph()

---

.travis.yml

to truly check build process before nightly builds

change travis matrix to zips

---

src/gui/button.c

https://www.deviationtx.com/forum/7-development/7008-devo-12s-no-button-inputs-after-renaming-mixer#61205

Fix no button inputs after renaming mixer

---

src/fs/common/template/4ch_dr.ini

Fix SRC for first mixer in AIL & ELE channels .

Fix  4ch_dr.ini template

---

src/gui/128x64x1/_bargraph.c

precompute constants to save ROM space on devo7E

---

src/protocol/flysky_afhds2a_a7105.c

Fix AFHDS-2A temperature telemetry value

Fix AFHDS-2A temperature telemetry

---

src/protocol/dm002_nrf24l01.c

Add one txid to DM002 protocol

Add one txid to DM002 protocol

---

src/Makefile
src/target/common/devo/msc2/mass_mal.c
src/target/common/stm32/spi_flash.c
src/target/devof12e-XMS/Makefile.inc
src/target/devof12e-XMS/capabilities.h
src/target/devof12e-XMS/char_map.h
src/target/devof12e-XMS/devof12e-XMS.ld
src/target/devof12e-XMS/lcd.h
src/target/devof12e-XMS/lcd_page_props.h
src/target/devof12e-XMS/target_defs.h
src/target/emu_devof12e-XMS/Makefile.inc
src/target/emu_devof12e-XMS/capabilities.h
src/target/emu_devof12e-XMS/channels.c
src/target/emu_devof12e-XMS/char_map.h
src/target/emu_devof12e-XMS/emu.h
src/target/emu_devof12e-XMS/lcd.c
src/target/emu_devof12e-XMS/lcd.h
src/target/emu_devof12e-XMS/lcd_page_props.h
src/target/emu_devof12e-XMS/mapped_gfx.c
src/target/emu_devof12e-XMS/target_defs.h
src/target/emu_devof12e-XMS/tw8816_map.c

For modded Devo F12E with upgraded flash memory chip

Add devof12e-XMS

---

src/config/display.c
src/config/voice.c

It doesn't fix any current error, since these functions are called only once, but it looks more correct.

Fix Devo12 "mymedia" calls

---

src/pages/128x64x1/pages.c
src/pages/320x240x16/pages.c
src/pages/common/_pages.c

Fix Quick Pages

---

src/gui/text/_bargraph.c

It fix devoF7 trim cursor position for first presses. it's the integer rounding problem, x / y changed to (x + y / 2) / y.

Fix text GUI trim bargraph

---

src/protocol/bayang_nrf24l01.c

Introduces Protocol format "X16-AH"

Support for new Bayang X16 with altitude hold feature

---

src/protocol/bayang_nrf24l01.c

Add IRDRONE format to Bayang protocol
Nothing special, standard channel mapping.
https://www.deviationtx.com/forum/protocol-development/7402-irdrone-ghost-x5-wifi-camera-xn297lbx-capture

Add IRDRONE format to Bayang protocol

---

src/protocol/sfhss_cc2500.c

Fix S-FHSS protocol servo throw

---

src/protocol/yd717_nrf24l01.c

The Use A.ACK option was added recently to accommodate nRF clone chips that don't support auto-acknowledge correctly.  This change missed updating the bind procedure, which uses auto-ack to skip binding if an already bound receiver is detected. The fix is to always go through the bind procedure when the option is set to No.
Reported in [forum post](https://www.deviationtx.com/forum/protocol-development/3452-solved-cx-10-binds-but-does-not-ack-packets#65766). 
Also fixes spelling.

Fix binding when auto-acknowledge is disabled.

---

src/protocol/frsky1way_cc2500.c

Values multiply by 1.5:
throw 100%: 400 * 1.5 = 600
center: 1500 * 1.5 = 2250 = 0x8CA

Fix Frsky-V8 protocol

---

src/protocol/sfhss_cc2500.c

- Fix for some S-FHSS receiver that didn't receive channel 4-8, now the RSFSB-B that's shipped with the T8SG has all8 channels working.
- Add failsafe support

S-FHSS fix

---

src/gui/128x64x1/_label.c

Fix issue "Main page text #330"

Fix vertical alignment for TINY_FONT (128x64x1 GUI)

---

src/config/model.c

https://www.deviationtx.com/forum/builds/7571-strange-behavior-of-devo-10

model.c: fix duplicate de/serialization of 'display-scale'

---

src/pages/320x240x16/chantest_page.c

I think it fix issue -> Unused input bars not hidden in input monitor #248

Fix "Input monitor" page

---

src/protocol/corona_cc2500.c

Fix Corona protocol modular build

Fix Corona protocol modular build

---

src/protocol/corona_cc2500.c

Simpler fix for maybe-uninitialized warning that doesn't break the protocol.

Fix Corona protocol

---

src/config/model.c
src/mixer.c
src/mixer.h
src/pages/common/advanced/_mixer_setup.c

You can add beeps to mixer. Mux "beep" repeat input value without changes.

Add mux type "beep"

---

src/protocol/hubsan_a7105.c

Add extra channels to the Hubsan H501 sub-protocol.
Channel 12: H123D mode selection, 3-way: Sport 1 / Sport 2 / Acro
Channel 13: H122D flip mode
Forums thread: https://www.deviationtx.com/forum/model-configs/7773-hubsan-h122d-devo-10-model-ini

Protocol Hubsan H122D / H123D, from goebish

---

src/protocol/flysky_afhds2a_a7105.c

Allow LQI output on Ch13 and Ch14, fixes https://github.com/DeviationTX/deviation/issues/422
Add telemetry for 2nd temperature sensor, fixes https://github.com/DeviationTX/deviation/issues/424

AFHDS 2A: Allow LQI output on Ch13 and Ch14

---

src/protocol/flysky_afhds2a_a7105.c

Allow LQI output on Ch13 and Ch14, fixes #422
Add telemetry for 2nd temperature sensor, fixes #424

AFHDS 2A: Allow LQI output on Ch13 and Ch14, from goebish

---

src/fs/language/lang.pt

https://www.deviationtx.com/forum/translations/7750-portuguese-br-translation

Add portuguese language for menus (tks user mchaves)

---

src/protocol/slt_nrf24l01.c

Add sub formats V2, Q100, Q200 and MR100 to SLT protocol
Channel mapping:
Channel 9: Flight Mode
Channel 10: Flip
Channel 11: Video On
Channel 12: Video Off (Q200), Picture Snapshot (Q100 / MR100)
Channel 13: Calibrate (Q100 / Q200)
Topic: https://www.deviationtx.com/forum/protocol-development/8017-slt-sub-protocols

Protocols SLT V2, Q100, Q200, MR100, from goebish

---

src/std.h
src/target/common/emu/Makefile.inc

cleanup OSX build as it is my main dev platform.

Fix emu build warning and error on OSX

---

src/Makefile
src/target/at9/Makefile.inc
src/target/common/devo/Makefile.inc
src/target/common/devo/devo.ld

* Add flock to make sure only one libopencm3 lib is built
* Generate optimize.ld in each target folder

Fix parallel build

---

src/protocol/assan_nrf24l01.c
src/protocol/bayang_nrf24l01.c
src/protocol/bluefly_nrf24l01.c
src/protocol/bugs3_a7105.c
src/protocol/bugs3mini_nrf24l01.c
src/protocol/cflie_nrf24l01.c
src/protocol/cg023_nrf24l01.c
src/protocol/cx10_nrf24l01.c
src/protocol/dm002_nrf24l01.c
src/protocol/e012_nrf24l01.c
src/protocol/e015_nrf24l01.c
src/protocol/esky150_nrf24l01.c
src/protocol/esky_nrf24l01.c
src/protocol/fq777_nrf24l01.c
src/protocol/fy326_nrf24l01.c
src/protocol/gw008_nrf24l01.c
src/protocol/h377_nrf24l01.c
src/protocol/h8_3d_nrf24l01.c
src/protocol/hisky_nrf24l01.c
src/protocol/hm830_nrf24l01.c
src/protocol/hontai_nrf24l01.c
src/protocol/inav_nrf24l01.c
src/protocol/kn_nrf24l01.c
src/protocol/mjxq_nrf24l01.c
src/protocol/mt99xx_nrf24l01.c
src/protocol/ncc1701_nrf24l01.c
src/protocol/slt_nrf24l01.c
src/protocol/symax_nrf24l01.c
src/protocol/v202_nrf24l01.c
src/protocol/yd717_nrf24l01.c

Remove MUSIC_Play from protocol, from howard0su

---

src/protocol/wfly_cyrf6936.c

Protocol was lacking CLOCK_StopTimer()

Fix WFLY protocol

---

src/telemetry.c

To make it fit devo7e if deemed useful

Shrink voice ROM usage

---

src/target/test/Makefile.inc
src/target/test/channels.c
src/target/test/emu.h
src/target/test/file.c
src/target/test/lcd.c
src/target/test/protospi.h
src/target/test/radio.c
src/target/test/sound.c
src/target/test/test_stubs.c

Remove the depedency of emu Makefile. Ready to move it out of target folder.
All the functions inside test folder can be mocked via variables or actions now.

Compile test as its own

---

src/target/common/devo/Makefile.inc

There is no flock on Windows. So don't do flock on Windows.

Don't try to flock on Windows

---

src/target/at9/Makefile.inc
src/target/common/devo/Makefile.inc

Prompt user to run git submodule init to get the libopencm3 code

Check libopencm3/Makefile before build

---

src/mixer.c

Reimplement mixer-dependency code to not store a complete copy of Model.mixers in stack.
Reduces stack usage of this function from ~2588bytes to ~380 bytes.  Code cost is ~68 bytes

Reduce stack usage of MIXER_SetMixers by ~2200 bytes

---

src/target/at9/tx_misc.c
src/target/common/devo/tx_misc.c

Tell the compiler we are using input paramter explictly.

Use right asm syntax for usleep

---

src/Makefile

One example is 'make CFLAGS_clock=xyz' to add xyz as CFLAGS for clock.c.

Add per file CFLAGS/CXXFLAGS

---

src/common.h
src/misc.c
src/protocol/spi/cyrf6936.c

This reverts commit 57ab702dbcd6ca77955b7d5e027d67528be98163.

Revert "Remove Delay, use usleep everywhere (#510)"

---

.travis.yml

Increase coverage of CI build

---

src/screen/320x240x16/lcd_string.c

font bits are not needed as global variables. allocate 80 bytes from stack

optimize font module for saving RAM

---

src/Makefile
src/target/common/devo/devo.ld
utils/check_string_size.pl
utils/extract_strings.pl

Parse .o file is not the best approach as some string can get optmized
out in link stage. LTO .o file even doesn't contain a string table.

Parse elf file to find out string table

---

.travis.yml

Re-write travis.yml to use build stages for build and release
The code is now cleaner, requiring less gnarly 'if' conditions.  Also only build pre-requisites that are actually used for each job

Cleanup travis build

---

src/config/tx.c
src/config/voice.c
src/config/voice.h
src/extended_audio.c
src/extended_audio.h
src/music.h
src/pages/320x240x16/voiceconfig_page.c
src/pages/common/_voiceconfig_page.c
src/pages/common/voiceconfig_page.h

Only read labels when inside voiceconfig menu by rerunning CONFIG_VoiceParse

Strip RAM needs for voice

---

src/gui/scrollbar.c

This should make it a little easier to hit the scrollbar by allowing touch anywhere on the bar, instead of just on the arrows

Enable scrollbar touch on bar instead of just arrows

---

src/target/at9/tx_buttons.c
src/target/at9/tx_buttons_isr.c

Also optimize handle_rotary_encoder a bit.

Split at9 button's ISR into a seperate file

---

src/target/test/make-tests.sh
src/tests/test_language.c

This make sure all tests are running in a determined order.

Sort the test cases by its name

---

src/config/model.c
src/config/model.h
src/pages/common/_telemconfig_page.c
src/telemetry.c
src/telemetry.h
utils/repack_ld.pl

the change is motivated by configure module change. With the change, the code can be written in data driven way.

Move telemetry data into one structure

---

src/common.h
src/config/model.c
src/config/model.h
src/mixer.c
src/pages/common/_chantest_page.c
src/pages/common/_model_config.c
src/pages/common/_model_page.c
src/tests/test_mixer.c

The RAM saving is only 1 byte, but the code is much more complex. use 2 bytes and cleanup the code.

split num_ppmin into num_ppmin_channels and num_ppmin_mode

---

.travis.yml

New linter seems to have regressions.  Let's lock down to a known 'good' one

Lock down cpplint version

---

src/target/drivers/display/8080/320x240x16.c
src/target/drivers/display/8080/320x240x16.h
src/target/drivers/display/8080/320x240x16_hx8347.h
src/target/drivers/display/8080/320x240x16_ili9341.h
src/target/drivers/display/8080/480x320x16_st7796.c
src/target/drivers/display/8080/480x320x16_st7796.h
src/target/tx/radiolink/at9/at9_ports.h

This LCD module is found on AT10S.

Add st7796 LCD driver

---

src/target/drivers/mcu/stm32/adc.c
src/target/drivers/mcu/stm32/clock.c
src/target/drivers/mcu/stm32/f1/dma.h
src/target/drivers/mcu/stm32/f1/nvic.h
src/target/drivers/mcu/stm32/f1/rcc.h
src/target/tx/devo/common/hardware.h
src/target/tx/devo/common/ports.h
src/target/tx/devo/common/protocol/pwm.c
src/target/tx/devo/common/pwm_isr.c
src/target/tx/devo/common/uart.c
src/target/tx/devo/common/uart_isr.c
src/target/tx/devo/devo12/devo12_ports.h
src/target/tx/devo/devo12/hardware.h

STM32 reorg: DMA abstraction

---

src/target/tx/devo/devof4-XMS/Makefile.inc
src/target/tx/devo/devof4-XMS/devof4-XMS.ld
src/target/tx/devo/devof4-XMS/devof4-XMS_opt.ld
src/target/tx/devo/devof4-XMS/protocol.ld
src/target/tx/devo/devof4/Makefile.inc
src/target/tx/devo/devof4/devof4.ld
src/target/tx/devo/devof4/devof4_opt.ld
src/target/tx/devo/devof4/protocol.ld
src/target/tx/devo/devof7-XMS/devof7-XMS.ld
src/target/tx/devo/devof7-XMS/devof7-XMS_opt.ld
src/target/tx/devo/devof7-XMS/protocol.ld

We had some remaining fallout from the reorganization.  his should fix all remaining targets

Fix make zips for DevoF4 and DevoF7

---

src/misc/fgets.c
src/target/drivers/filesystems/syscalls.c

Conversion from void * to uintptr_t should have been intptr_t in file-handling code

Fix segfault in filehandling

---

src/target/drivers/display/i2c/video_tw8816.c
src/target/drivers/mcu/stm32/f1/freq.h
src/target/drivers/mcu/stm32/f1/gpio.h
src/target/drivers/mcu/stm32/gpio.h
src/target/drivers/mcu/stm32/i2c.h
src/target/tx/devo/common/ports.h
src/target/tx/devo/devof12e-XMS/target_defs.h
src/target/tx/devo/devof12e/hardware.h
src/target/tx/devo/devof12e/target_defs.h

STM32 reorg: Remove hard-coded I2C values for Devof12e

---

src/target/drivers/mcu/stm32/exti.h
src/target/tx/devo/devo12/devo12_ports.h
src/target/tx/devo/devo12/hardware.h

Missed some devo12 configuration during TIMER reorg

Fix PWM support for devo12

---

src/target/tx/devo/ir8m/target_defs.h
src/target/tx/devo/t8sg/target_defs.h
src/target/tx/devo/t8sg_v2/target_defs.h
src/target/tx/devo/t8sg_v2_plus/target_defs.h

Fix duplicated txid

---

src/target/drivers/mcu/stm32/tim.h
src/target/tx/devo/common/protocol/pwm.c

This is a potential fix for ppm/pwm not working.  it has not yet been tested on a real tx yet

Fixes for PPM/PWM

---

src/protocol/usbhid.c
src/target/drivers/usb/devo_hid.c

Remove PrevXferComplete from usbhid

---

src/config/model.c
src/config/model.h
src/pages/common/_model_page.c

Working and hopefully cleaner fix to replace #670.

Fix index out-of-bounds and null pointer in power settings

---

src/protocol/crsf_uart.c

Add support for 250mW power level in CRSF telemetry.

---

src/target/drivers/mcu/stm32/spi.h
src/target/tx/devo/common/hardware.h
src/target/tx/radiolink/common/hardware.h

Thanks to Goebish for finding this doozy

Fix inconsistency in SPI baud-rate setting resulting in wrong spi speed

---

src/protocol/spi/nrf24l01.c
src/target/drivers/mcu/emu/protospi.h
src/target/tx/devo/common/protospi.h
src/target/tx/opentx/x9d/protospi.h
src/target/tx/other/test/protospi.h
src/target/tx/radiolink/common/protospi.h
src/universaltx/include/protospi.h

Revert nrf24 spi cs patch, root cause fixed in #787

Revert nrf24 spi cs patch

---

src/target/drivers/mcu/stm32/tim.h
src/target/drivers/sound/piezo/sound.c

@hexfet This should fix the issue with SSER running at the wrong frequency

Timer runs at 2xAPB? not 1xAPB?

---

src/target/drivers/mcu/stm32/f1/jtag.h
src/target/tx/devo/common/spi_proto.c

This should fix using Deviation with the new bootloader

Enable AFIO and ensure the CYRF6936 reset pin is configured

---

src/protocol/bugs3mini_nrf24l01.c

[Bugs3Mini] Fix flips

---

src/protocol/e016h_nrf24l01.c

Add calibration flag for E016H format.
Works same as stock controller, set both sticks to external bottom corners to start accelerometer calibration.

[E016H protocol] Add calibration flag

---

src/protocol/bugs3mini_nrf24l01.c

Add some rocket fuel to the Bugs3Mini
https://www.deviationtx.com/forum/protocol-development/7850-bugs-3-mini?start=200#73889

Protocol bugs3mini dynamically driven trims

---

ChangeLog.md
src/protocol/bugs3mini_nrf24l01.c

Add Bugs 3H format option to Bugs3Mini protocol
Channel 10: Altitude hold

Add Bugs 3H format option

---

src/protocol/bayang_nrf24l01.c

Add DHD D4 and H8S 3D format options to Bayang protocol

Add DHD D4 and H8S 3D formats

---

src/protocol/wfly_cyrf6936.c

Add frequency tuning option to WFLY protocol

Add frequency tuning option to WFLY protocol

---

src/protocol/wfly_cyrf6936.c

Add frequency tuning option to WFLY protocol

Add frequency tuning to WFLY protocol, from goebish

---

src/pages/128x64x1/telemtest_page.c
src/pages/320x240x16/pages.c
src/telemetry.c

Fix telemetry reset repeating. Add telemetry reset sound indication.

Fix telemetry reset repeating

---

src/target/tx/devo/t8sg/target_defs.h
src/target/tx/devo/t8sg_v2/target_defs.h
src/target/tx/devo/t8sg_v2_plus/target_defs.h

Reverts DeviationTX/deviation#945

Revert "Disable Multimod support for t8sg series"

---

src/protocol/kn_nrf24l01.c

The V977 stock transmitter send all (working) trims (T, A, E, R). This is to make the Deviation perfectly the same as a stock V977 transmitter

KN protocol 12 channels

---

src/protocol/flysky_afhds2a_a7105.c

Reverts DeviationTX/deviation#957

Revert "Fix Flysky external voltage sensor"

---

src/protocol/flysky_afhds2a_a7105.c

Reverts DeviationTX/deviation#938

Revert "Add support for Flysky AC type telemetry, from hexfet"

---

src/main.c
src/misc/misc.c
src/target/tx/devo/devo7e-256/target_defs.h
src/target/tx/devo/ir8m/target_defs.h
src/target/tx/devo/t8sg/target_defs.h
src/target/tx/devo/t8sg_v2/target_defs.h
src/target/tx/devo/t8sg_v2_plus/target_defs.h

USB drive erase procedure:
1. "Power ON" transmitter with USB mode (ENT + Power ON)
2. Press "UP" button
3. After short beep press "DOWN" button
4. After short beep "Power OFF" transmitter
5. "Power ON" transmitter with USB mode (ENT + Power ON)
6. Format transmitter USB drive with "Quick Format" option enabled

Add "USB drive erase" procedure

---

src/pages/128x64x1/advanced/mixer_curves.c

Solves https://github.com/DeviationTX/deviation/issues/995

Wait for button release for exiting

---

src/protocol/redpine_cc2500.c

Fix redpine initialization for modular builds.

---

src/protocol/frskyx_cc2500.c

Based on an update of the MPM code. All thanks go to Pascal for doing the fix. 
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/543

Fix bind problem for FrSky XM+ v2.1.2 firmware

---

src/protocol/crsf_uart.c

Use CRSFshot "offset" telemetry to synchronize packet sends with the
transmitter module.  This reduces latency by delivering data to the
transmitter in sync with when the transmitter will use it.
Prior to this change a Crossfire TX LCD shows "CRSF V2" for the RC
Input.  After this change the display is "CRSFshot".

Implement CRSFshot synchronization between tx and radio

---

src/protocol/cx10_nrf24l01.c

update for Q222 v1 based on multiprotocol module, still not compatible with v2 tough

J0e57 patch 1

---

src/crsf.h
src/pages/128x64x1/crsfdevice_page.c
src/pages/common/_crsfdevice_page.c
src/protocol/crsf_uart.c

Updates from the tx were being filtered out.

Bug fix for COMMAND parameter
