- src/protocol/flysky_a7105.c
Newer FlySky receivers don't work with a packet period of 1460us.  
Quoting hpnuts:  
"Turnigy 9X Flysky module v2 is 1533, New Flysky TX module for 9XR/9XR Pro is 1510 (the one using the internal antenna) , brand new V911 TX is 1490.
1460 does not work but increasing to 1480 works. I kept 1510 has a middle value and tested it on all my RXs: flysky RX 3&6&8 channels, V911 and F939."
> Fix FlySky packet period

- src/protocol/h8_3d_nrf24l01.c
Push both stick bottom right to calibrate accelerometer on JJRC H20 / H11D
> Add accelerometer calibration flag for JJRC H20 / H11D

- src/protocol/h8_3d_nrf24l01.c
Fix rf channel hopping calculation for H8_3D protocol, as noticed by mjbudden:
http://www.deviationtx.com/forum/protocol-development/4724-jjrc-h20-hex-quad?start=160#50020
> Fix rf channel hopping for H8_3D protocol

- src/protocol/mjxq_nrf24l01.c
Add E010 format to MJXq protocol, compatible with EAchine E010, NuHui NH-010 and probably JJRC H36 mini.
- Channel 6: flip mode
- Channel 9: Headless
- Channel 10: RTH
> Add E010 format to MJXq protocol

- src/protocol/dsm2_cyrf6936.c
Changes at DSM2/X protocol:
1. Removed unnecessary CYRF programming.
2. Changed use of channels maps. Now protocol will use 3 channel maps only => up to 7 channels, 8 to 12 channels and channels map for "High Speed" 11ms mode.
3. Corrected error at PN codes table.
4. Added "OrangeRX" protocol option to fix error at PN codes table.
5. Added "High Speed" 11ms protocol option. It work for 8-10 channels modes only.
6. Added "CYRF reset" in case TX mode and RX mode freezed with telemetry enabled. It's very rare case, but really can happen.
7. Initial implementation for "Flight Log" filtering. It's remove "Spektrum telemetry range warning" garbage. It's do not fit to Devo7e and cut out from code for Devo7e.
8. Added negative GPS altitude (below sea level).
All changes tested and work fine.
> Changes at DSM2/X protocol

- src/protocol/mjxq_nrf24l01.c
Add JJRC H26WH format option to MJXq protocol.
Channel 5: Arm
As for the H26D, this sub-format has only one set of RF channels, interferences ~~can~~ will occur if multiple Deviated transmitters are using this sub format simultaneously.
This PR also replaces the semi arbitrary txid for E010 with a list (8) of IDs/RF channels captured from stock transmitters, this fixes this issue: https://github.com/goebish/nrf24_multipro/issues/17 
The MJXq protocol is a strange beast, looks like every sub-format is using a different TXID/RF channel relationship, they're not interchangeable.
> Add protocol for JJRC H26WH

- src/protocol/frsky2way_cc2500.c
- src/protocol/spi/cc2500.c
When receiving hub telemetry the receiver expects the sequence number in the telemetry packet to be echoed back in packet[4] of transmitted packets.  Without this acknowledgement the D4R-II receiver only cycles through 0-7 sequence numbers and repeats unacknowledged data.  When the proper response is sent the D4R-II cycles the sequence number 0-31 without repeating data.
The change to CC2500_SetTxRxMode() turns off the LNA before enabling the PA when entering transmit mode.  Wasn't causing a problem; just good practice.
> Update Frsky to fix hub telemetry

- src/protocol/frsky2way_cc2500.c
- src/protocol/frskyx_cc2500.c
Properly initialize telemetry and set telemetry type by protocol, not by modelXX.ini file
> Fix initialize telemetry and set telemetry type for Frsky

- src/config/display.c
- src/config/hardware.c
- src/config/language.c
- src/config/model.c
- src/config/tx.c
- src/telemetry.c
Changed counters type to u32 or s32 for compacting binary ("config" folder only).
After that I can fit "Fix telemetry items loading for CFlie and AFHDS 2A protocols" to Devo7e.
> Fix telemetry items loading for CFlie and AFHDS 2A protocols

- src/protocol/Makefile.inc
- src/protocol/protocol.c
- src/protocol/spi/cyrf6936.c
Since HAS_4IN1_FLASH is not defined it doesn't hurt to anything, but will simplify synchronization of protocols with "master" branch.
> "protocol" folder synchronization

- src/target/devof12e/tw8816.c
- src/target/devof12e/tw8816_init_1.3.h
1.3a settings work well for me. To test it for a wider audience we need to have nightly build available.
> Use known good settings for F12E video.

- src/protocol/q303_nrf24l01.c
Add CX10D & CX10WD formats to Q303 protocol, also add (semi) arbitrary transmitter ID for CX35.
Channel 5: auto land (below 0) / manual (0) / auto take off (above 0)
Channel 6: flip
Forums thread: https://www.deviationtx.com/forum/protocol-development/6448-cx-10d-traces
> Add CX10D & CX10WD formats to Q303 protocol

- src/protocol/q303_nrf24l01.c
Add CX10D & CX10WD formats to Q303 protocol, also add (semi) arbitrary transmitter ID for CX35.
Channel 5: auto land (below 0) / manual (0) / auto take off (above 0)
Channel 6: flip
Forums thread: https://www.deviationtx.com/forum/protocol-development/6448-cx-10d-traces
> Add CX10D & CX10WD formats to Q303 protocol, from goebish

- src/target/devo12/Makefile.inc
zip -x option has to be last in command line. It will work with any Info-ZIP version, not v3.0 only.
> Fix "zip" command line

- .travis.yml
FLTK versions other than "fltk-x.x.0" are not suitable for dynamic builds. Therefore, next version we can use will be "fltk-1.4.0".
> Fix emulator build warnings

- src/protocol/frskyx_cc2500.c
This change adds a FrskyX protocol option for EU firmware compatibility.  Select Format protocol option to EU to work with EU receiver firmware.  Set option to FCC for standard firmware.
Thanks to midelic and Mike for the implementation from the DIY multiprotocol project.
> Frsky EU firmware support

- src/pages/common/model_page.h
With "u16 total_items" devo10 emulator crashed if I try to change default model icon. With "u8 total_items" it is OK.
It was changed from "u8" to "u16" with "Pull Request #128: Increase maximum number of model files from 100 to 255"
> Fix change model icon

- src/target/devof12e/tw8816.c
At boot time empty XY-graph placeholder overlay "Splash" and "Safety Warning" pages and cut off portion of image.
> Fix XY-graph placeholder overlay "Splash" page for Devo F12E

- src/pages/128x64x1/standard/common_standard.c
- src/pages/128x64x1/standard/curves_page.c
- src/pages/128x64x1/standard/drexp_page.c
- src/pages/text/standard/common_standard.c
- src/pages/text/standard/curves_page.c
- src/pages/text/standard/drexp_page.c
I can't find the reason why "D/R & Expo" page crashed with "text" GUI, so I send it as is. At least it is not worse then before.
> Fix "text" GUI "Standard" - "Curves" pages

- src/gui/image.c
- src/screen/320x240x16/lcd_gfx.c
I don't know how it worked before, but image_read_header() read width only and always height=0.
> Fix mapped images support

- src/pages/common/_debuglog_page.c
1. Fix Windows built emulator crash at debuglog page
2. Fix debuglog circularity at debuglog page. Debuglog entries repeated 2, 3, 4... times at debuglog screen, depending from length of entries.
Now it is clear that the size of the debuglog is too small. It can contain very limited number of entries.
In my case it can contain 15 entries: "Backlight: X", thats all. 13 x 15 = 195 and debuglog size = 200.
> Fix debuglog page

- src/target/devof12e/tw8816.c
Previous version overwrite "Flat Panel Horizontal Synchronization Period" settings, if it changed.
> Fix TW8816_ReinitPixelClock()

- src/pages/128x64x1/advanced/mixer_setup.c
- src/pages/128x64x1/standard/drexp_page.c
With corrected scaling XY-graph has more nice look (straight line) with "Scale=125%".
> Fix XY-graph scaling for 128x64x1 GUI

- doc/CFlie_NRF24L01.txt
- src/protocol/cflie_nrf24l01.c
Adding support for a new packet type for the Crazyflie 2.0 -- CPPM emulation via the NRF radio. Allows for flexible channel support and re-mapping. Eliminates need to hardcode max angle/rates in the deviation protocol code.
> cflie_nrf24l01 protocol support for CPPM CRTP commander type

- src/protocol/bayang_nrf24l01.c
This is the "emergency stop channel" which works on the boldclash b-03 quad. Because of the altitude hold, this is needed if the quad fails to detect landing. Uses channel 12.
There are 2 other channels which are not implemented due to lack of room ( all 12 channels are used ) they are auto takeoff/land and "heavy lift mode" whatever that is, not as important as stop channel.
Tested on 7e
A new model file needs to be made because the number of channels is saved in it, and this is channel 12, it won't show otherwise.
The quad acts on channel change only.
> Added extra channel for bayang protocol

- src/protocol/flysky_afhds2a_a7105.c
Telemetry update for Flysky/Turnigy AFHDS 2A protocol
- RSSI now reported as a positive number, allowing to set an alarm (min = 60, the lower the better)
- Report Link Quality as LQI (max = 100, the higher the better), probably a better indicator than RSSI
- External IBUS voltage sensors support, only 1 for 7e (modular build), 2 for other platforms, VOLT2 & VOLT3
- External IBUS RPM sensor support, only 1 sensor supported (not available on 7e)
- Built in external voltage sensor support (IA6C, X6B RXs...), not available on 7e
- External IBUS temperature sensor support, not tested, not available on 7e
> AFHDS 2A telemetry update

- src/protocol/h8_3d_nrf24l01.c
Add H20H format to H8_3D protocol 
- CH5 = motors on/off
> Add H20H format to H8_3D protocol 

- doc/CFlie_NRF24L01.txt
- src/protocol/cflie_nrf24l01.c
Added 'simple' telemetry mode that reads RSSI and VBat (if present) out
of the NRF ACK packet. This will be faster and require less overhead
than establishing a full CRTP logging session, but cannot be extended
beyond RSSI/Internal VBat.
Also did a bit of refactoring of the CRTP logging code, and added RSSI
to the logging block.
> CFlie: Adding 'simple' telemetry mode

- src/protocol/flysky_afhds2a_a7105.c
Add a protocol option to output LQI on an AUX channel, allowing OSDs to display signal quality.
discussion: https://www.deviationtx.com/forum/protocol-development/5251-flysky-afhds-2a-protocol-as-used-i10-i6-it4?start=480#62315
> AFHDS-2A LQI output protocol option

- src/config/model.h
- src/protocol/flysky_afhds2a_a7105.c
Add a protocol option to output LQI on an AUX channel, allowing OSDs to display signal quality.
discussion: https://www.deviationtx.com/forum/protocol-development/5251-flysky-afhds-2a-protocol-as-used-i10-i6-it4?start=480#62315
> AFHDS-2A LQI output protocol option, from goebish

- doc/CFlie_NRF24L01.txt
- src/protocol/cflie_nrf24l01.c
Added 'simple' telemetry mode that reads RSSI and VBat (if present) out
of the NRF ACK packet. This will be faster and require less overhead
than establishing a full CRTP logging session, but cannot be extended
beyond RSSI/Internal VBat.
Also did a bit of refactoring of the CRTP logging code, and added RSSI
to the logging block.
> CFlie: Adding 'simple' telemetry mode, from theseankelly

- src/pages/common/_toggle_select.c
The space character after "mymedia/toggle3 " break use of "mymedia/toggle3.bmp".
> Fix use of Devo12 "mymedia\toggle3.bmp"

- src/config/hardware.c
> bugfix: break when audio_player found

- src/protocol/frskyx_cc2500.c
Detailed information about the FrskyX packet sequence number algorithm was [posted here](https://www.rcgroups.com/forums/showpost.php?p=37966054&postcount=181) a few days ago.  Thanks to Mike Blanford.   With this change missed packets are recovered without resetting the telemetry link so overall telemetry throughput is increased.  Tested on XSR with both FCC and EU firmware.
> Frskyx sequence number algorithm improvement

- src/mixer.c
> Add missing "break" to make mux delay working again

- src/mixer.c
- src/mixer.h
- src/pages/common/_trim_page.c
Adds the ability to use the momentary trim switches as 3 pos switches.  ie, normal resting position is centred (`0`), while pressing the trim one way or the other results in a momentary deflection in one direction (`-100`) or the other (`+100`).
I used this together with "Adjustments" in Betaflight to allow easy adjustments to my PID's.
> Add 3pos trim switch functionality

- src/protocol/flysky_afhds2a_a7105.c
AFHDS 2A channel scaling was slightly off, as reported here:
https://www.deviationtx.com/forum/protocol-development/5251-flysky-afhds-2a-protocol-as-used-i10-i6-it4?start=540#64452
edit: also fixes this issue
https://www.deviationtx.com/forum/6-general-discussions/7357-devo-7e-problem-changing-output-power-afhds-2a
> Fix AFHDS 2A channel scaling & tx power not in sync

- src/telemetry/telem_frsky.c
Adjust min/max values to match actual possible range (-7 to -198).  The LRSSI value is an estimate in dBm according to the procedure of section 17.3 of the datasheet.
>  Fix min/max limit values on LRSSI so alarm can be set on LRSSI. 

- src/main.c
I know this is not the perfect solution, as it discards mux voice alert completely on transmitter startup, on the other hand mixers get checked so early after startup there really seems to be no choice to it unless we start digging deeper.
>  Prevent mux voice from triggering sound before welcome has played.

- src/protocol/flysky_a7105.c
- src/protocol/flysky_afhds2a_a7105.c
- src/protocol/hubsan_a7105.c
- src/protocol/iface_a7105.h
- src/protocol/joysway_a7105.c
- src/protocol/spi/a7105.c
Add fine frequency tuning option to A7105 protocols, same as CC2500 protocols.
This is required for some A7105 modules or Rx with inaccurate crystal oscillators.
Forums thread: https://www.deviationtx.com/forum/6-general-discussions/7376-jumper-t8sg-and-e010s-flysky-afhds-latency
More and more people are having the same issue with 256 kbps xn297 protocols (eg E010), unfortunately there's nothing we can do in software to fine tune the nrf24l01. X-in-1 modules manufacturers should use better accuracy crystals, especially for the nrf24l01 (+/-20ppm because of the xn297 emulation, despite the nrf24 datasheet specifies +/-60ppm,  ...). I'll expose the issue to Jumper.
> Add fine frequency tuning option to A7105 protocols

- src/protocol/frskyx_cc2500.c
Timing change fixes issue with telemetry when using LBT option.  Enters receive mode a little sooner and listens a little longer.  This change comes from the DIY-Multimodule project.
Have tested with Frsky XSR receiver.  Both CPPM and SBUS outputs are unaffected.
> Frskyx timing

- src/Makefile
- src/config/model.c
- src/mixer.c
- src/mixer.h
- src/pages/common/_main_page.c
I wanted to be able to specify channels in ranges other than [-100, 100] %. For example, I may want to map [-100, 100] % to [-1000, 1000] RPM. I've added the ability to specify the scale factor as well as the `sprintf` format string to facilitate this. To override, specify `display-scale=xxx` and/or `display-format=sss` in a particular channel section of `model.ini`. If `display-scale` or `display-format` are not specified, the default format is used. These options are only exposed by manually editting the `model.ini` file.
> Add ability to specify display scale/format string

- src/mixer.c
I've fixed `MIXER_GetChannelDisplayScale`/`MIXER_GetChannelDisplayFormat` when used with a virtual channel (discovered in #340). I added a similar check used by [MIXER_ApplyLimits](https://github.com/DeviationTX/deviation/blob/e292f38af3a8188e0d6de0b0e9827cc147a7c5a5/src/mixer.c#L389) and [MIXER_GetLimit](https://github.com/DeviationTX/deviation/blob/e292f38af3a8188e0d6de0b0e9827cc147a7c5a5/src/mixer.c#L659).
> #340 fix MIXER_GetChannelDisplayScale/Format

- src/telemetry.h
- src/telemetry/telem_frsky.c
The Volt3 value was incorrectly labeled Volt5/TelemV5 when configuring alerts and main page boxes.  Changed to display correctly.  Added comments where enums must be in order for correct display.
This will break model files that have configured an alert or display box for Volt5/TelemV5, but the effect is just to set the alert/box content to None.  Doubtful anyone has tried to display this since Volt3 is not normally in the Frsky telemetry stream.
> Fix Frsky volt3 telemetry display

- src/telemetry.h
- src/telemetry/telem_frsky.c
The Volt3 value was incorrectly labeled Volt5/TelemV5 when configuring alerts and main page boxes. Changed to display correctly. Added comments where enums must be in order for correct display.
This will break model files that have configured an alert or display box for Volt5/TelemV5, but the effect is just to set the alert/box content to None. Doubtful anyone has tried to display this since Volt3 is not normally in the Frsky telemetry stream.
> Fix Frsky volt3 telemetry display, from hexfet

- src/pages/common/_trim_page.c
https://github.com/DeviationTX/deviation/commit/2c5dda00cebad64b7689d3f0dc328dbd69f710a4#diff-37a3cf31eac0c0a3ec01d4a28a7f9d6d
The reason; it breaks intended functionality.
https://www.deviationtx.com/forum/3-feedback-questions/1274-independent-trims-for-flight-modes?start=40#67242
> Revert fix for #600

- src/config/model.c
- src/mixer.c
- src/mixer.h
You can use 4-6 contiguous virtual channels to setup 4-6 pos switch, then assign to trims "Switch" the first used virtual channel and you will have 4-6 independent trims set. The virtual channels switch at any state should have only single channel with +100% value, all others -100%. It's intended for for 4-6 flight modes with independent trims settings.
> Add support for 6 independent trims set

- src/mixer.c
- src/mixer.h
- src/pages/common/_trim_page.c
Adds the ability to use the momentary trim switches as 3 pos switches. ie, normal resting position is centred (0), while pressing the trim one way or the other results in a momentary deflection in one direction (-100) or the other (+100).
> Add 3pos momentary trim switch, from DavidBoone

- src/target/t8sg/target_defs.h
It has not sense for transmitter with integrated 4in1 module. Probably we can disable 4IN1_FLASH support for all transmitters with plenty flash memory.
> Disable 4IN1_FLASH support for T8SG

- src/config/display.c
- src/config/display.h
- src/fs/320x240x16/media/config.ini
- src/gui/320x240x16/_gui.c
- src/gui/480x272x16/_gui.c
You can select to draw background instead a background image for color GUI. This will greatly speed up the drawing of the pages. You can set header color and background color. The settings are in "config.ini" file. By default used background image.
```
[background]
drawn_background=0
bg_color=50A0D8
hd_color=707070
```
> Add selectable and configurable drawn background

- src/pages/320x240x16/voiceconfig_page.c
It fix the devo8 and devo12 "Voice config" page "External voice currently not available" has not [Exit] button as all other pages.
> Fix color GUI "Voice config" page

- src/protocol/ppmout.c
- src/target/at9/at9_stubs.c
- src/target/common/devo/Makefile.inc
- src/target/common/devo/ports.h
- src/target/common/devo/protocol/pwm.c
- src/target/common/devo/pwm_rom.c
- src/target/common/devo/uart.c
- src/target/devo12/devo12_ports.h
- src/target/x9d/x9d_ports.h
- src/target/x9d/x9d_stubs.c
Uses timer to generate ppm output pulses, replacing current method of bit-banging based on clock timer callbacks.  This improves control of the pulse width to reduce jitter.
The implementation is based on the timer code that had been commented-out in pwm.c, which needed fixes for defines and co-operation with usart using the same pin.  The basic logic was correct.  Some usart code is also updated for co-operation.
This has been tested with devo10 and t8sg.  Needs devo12 and modular build testing as those are slightly different.  [Test builds available](https://www.deviationtx.com/downloads-new/category/818-hexfet-ppm-timer).
> Timer-based PPM protocol

- src/main.c
With drawn background added delay 0.3sec in order to extended sound device be ready to set volume.
> Fix startup sound volume with drawn background

- src/pages/320x240x16/main_layout.c
- src/pages/common/_main_layout.c
It will properly fix: 
1) issue #297 - move layout items at 320x240 GUI,
2) introduced bug - the main layout toggle icon position will reset to x=0 y=32 after toggle icon change/selection,
Also, changed to remove dialog object, since remove dialog object by self will remove all hierarchical objects.
> Proper fix for issue #297 and introduced bug

- src/target/devof4-XMS/Makefile.inc
- src/target/devof4-XMS/target_defs.h
- src/target/devof7-XMS/Makefile.inc
- src/target/devof7-XMS/target_defs.h
Because of lack of memory for future updates.
> Disable datalog for devof4-XMS and devof7-XMS

- src/gui/gui.c
- src/gui/gui.h
- src/gui/scrollable.c
- src/pages/128x64x1/advanced/mixer_limits.c
- src/pages/128x64x1/main_layout.c
- src/pages/320x240x16/advanced/mixer_page.c
- src/pages/320x240x16/chantest_page.c
- src/pages/320x240x16/main_layout.c
- src/pages/320x240x16/standard/drexp_page.c
- src/pages/320x240x16/standard/failsafe_page.c
- src/pages/320x240x16/standard/reverse_page.c
- src/pages/320x240x16/standard/subtrim_page.c
- src/pages/320x240x16/standard/traveladj_page.c
- src/pages/320x240x16/timer_page.c
- src/pages/320x240x16/toggle_select.c
- src/pages/320x240x16/tx_configure.c
- src/pages/common/_main_config.c
- src/pages/common/_main_layout.c
- src/pages/common/_model_page.c
* Avoid full page redraw for any scrollable object change. It looks much more naturally if updated the scrollable area only, but not the full page.
* Avoid full page redraw with every item position change at "Main layout edit" page.
* Avoid full page redraw after close any dialog window.
* Optimize redraw objects after close dialog window, redraw underlying objects only.
> Optimize GUI redraw

- src/target.h
- src/target/common/devo/uart.c
Support for SBUS requires non-standard data rate and parity and stop bit changes.  Other serial protocols need similar control.
> Update UART_ API to support serial protocol development

- src/pages/128x64x1/dialogs.c
- src/pages/320x240x16/dialogs.c
- src/pages/common/_dialogs.c
We can't use "tempstring" for early warnings (such as "Missing modules"), since "tempstring" used by draw screen and will be overwritten before warning will draw.
> Fix display of text in startup warnings

- src/protocol/hubsan_a7105.c
Add extra channels to the Hubsan H501 sub-protocol.
Channel 12: H123D mode selection, 3-way: Sport 1 / Sport 2 / Acro
Channel 13: H122D flip mode
Forums thread: https://www.deviationtx.com/forum/model-configs/7773-hubsan-h122d-devo-10-model-ini
> Protocol Hubsan H122D / H123D

- src/music.c
More elaborate fix to come in the next version of the voice menu.
> Temporary fix for enabling device=buzzer in MUSIC_PlayValue

- src/protocol/frsky2way_cc2500.c
Add optional RSSI channel to Frsky D8 protocol, same as FrskyX (D16) and AFHDS-2A protocol.
Tested with D4R-II Rx and random Chinese D8 Rx.
> Frsky D8: Add optional RSSI channel

- src/buttons.c
- src/buttons.h
It seems button debouncing was planned, but the define for DEBOUNCE_WAIT_MS was never actually used.
> Fixed button debouncing

- src/common.h
- src/config/model.c
- src/pages/128x64x1/advanced/mixer_setup.c
- src/protocol/cx10_nrf24l01.c
- src/protocol/esky150_nrf24l01.c
- src/protocol/flysky_afhds2a_a7105.c
- src/protocol/hubsan_a7105.c
- src/protocol/j6pro_cyrf6936.c
- src/protocol/kn_nrf24l01.c
- src/protocol/mjxq_nrf24l01.c
- src/protocol/wfly_cyrf6936.c
Fix warnings notified by new gcc.
1. Access array out of range
2. explicit on fall through in switch branches.
> Fix warnings under new gcc

- src/pages/common/_pages.c
- src/telemetry.c
- src/telemetry.h
As most protocol doesn't support telemetry, make unsupport as 0 to save
ROM size 264 bytes. Also fixed the places which assumes the values.
For example of devof12e:
before:
ROM: 0x08004000 - 0x0803c13c = 224.31kB
RAM: 0x20000000 - 0x200069f8 =  26.49kB
After:
ROM: 0x08004000 - 0x0803c034 = 224.05kB
RAM: 0x20000000 - 0x200069f8 =  26.49kB
> Make PROTO_TELEM_UNSUPPORTED to 0

- src/pages/common/_main_page.c
first, the code cannot handle any size other than 6x4.
second, the unit of image size is pixel, while mapped gfx window is
char. They cannot use mixed. Let's always use 6x4 for devof12e.
> Don't use image size to create mapped gfx

- src/common.h
- src/config/model.c
- src/pages/128x64x1/model_config.c
- src/pages/320x240x16/model_config.c
- src/pages/common/_model_page.c
- src/protocol/protocol.c
Use an array Protocols to expose various data to avoid big switch in the code.
This saves another 492bytes from devo7e build.
> rework the way to expose protocol data

- src/protocol/v911s_nrf24l01.c
This can lead to accidentally override other variable to zero.
> Fix memory access out of range issue

- src/common.h
- src/protocol/protocol.c
We need channel mapping after we load the protocol, and before initialize the protocol. Fix this to align with the original logic.
> Set channel mapping during PROTOCOL_Load

- src/target/common/emu/Makefile.inc
Latest OSX mojava has the build failure. Fix it via passing the correct CFLAGS and LDFLAGS.
> Fix fltk build after migrate to latest osx

- src/config/model.c
- src/mixer_standard.c
- src/protocol/interface.h
- src/protocol/protocol.c
Channel mapping doesn't work expected in some protocol modules due to the variables are not initialized proper in the modular. Use a number instead of pointer to return from modular and convert it to the real pointer in main firmware.
> Fix regression on channel mapping

- src/config/language.c
- src/pages/common/_lang_select.c
- utils/extract_strings.pl
This change introduced a new file format for lang.* under language folder. The file is formatted in the way:
Line 1: <BOM>LanguageName
Line2-N: <16bit FNV Hash of english string>Localized String
The change increases the performance switching the language as we don't only read half of the content and don't need calculate hash as the hash is compute during build.
The change significantly reduces the size of localized file. After this change, I can successfully pack all localization files into 64KB SPI flash on F12E.
> New Format of localization File

- src/config/model.h
- src/extended_audio.c
- src/extended_audio.h
- src/mixer.c
- src/music.h
- src/pages/128x64x1/guiobj.h
- src/pages/128x64x1/pages.c
- src/pages/320x240x16/guiobj.h
- src/pages/320x240x16/pages.c
- src/pages/text/guiobj.h
- src/pages/text/pages.c
- src/protocol/assan_nrf24l01.c
- src/protocol/dsm2_cyrf6936.c
- src/protocol/ppmout.c
- src/protocol/usbhid.c
- src/target/common/devo/Makefile.inc
- src/target/common/devo/hid/hid_usb_istr.c
- src/target/common/devo/proto_stubs.c
- src/target/common/devo/spi_proto.c
Make sure we only declare variables in header files. Move allocation to .c file. Also declare the local variables with "static".
> Cleanup variable declaration

- src/target/common/devo/power.c
After powering up in USB mode, the next press of the power button would cause immediate reset on T8SG V2 transmitters.  The CheckPowerSwitch function assumed it was being called every 5ms from the event loop.  That's not true after powering up in USB mode.  Changed the function to be independent of call rate.
> Fix issue with exiting USB mode in t8sg V2 transmitters. 

- src/config/language.c
this gets broken accidently when I introduce new format of language file.
> Fix CONFIG_EnableLanguage

- src/config/language.c
Moving back file cursor should use SEEK_CUR instead of SEEK_SET.
> Fix typo in language file read

- src/target/common/devo/hid/hid_devo.c
- src/target/common/devo/msc2/lib/usb_core.c
- src/target/common/devo/msc2/lib/usb_core.h
- src/target/common/devo/msc2/lib/usb_init.c
- src/target/common/devo/msc2/lib/usb_init.h
- src/target/common/devo/msc2/usb_devo8.c
- src/target/common/devo/msc2/usb_prop.c
Some versions of compiler can detect this but some cannot. Don't rely on compiler to do this instead of make it explicit on which structure is const. Also change the type to make sure no warnings.
> Make some USB structure as const to save some RAM

- src/music.c
1. Parse the name of tone instead of a table.
2. Only store one scale of freq and caculate others.
> Reduce ROM usage of music module

- src/pages/128x64x1/guiobj.h
- src/pages/128x64x1/pagelist.h
- src/pages/128x64x1/pages.h
- src/pages/128x64x1/scanner_page.c
- src/pages/320x240x16/pages.h
- src/pages/320x240x16/scanner_page.c
- src/pages/320x240x16/scanner_page.h
- src/pages/480x272x16/scanner_page.h
- src/pages/common/_pages.h
- src/pages/common/_scanner_page.c
- src/pages/common/scanner_page.h
- src/target/devo10/target_defs.h
- src/target/devo12e/target_defs.h
- src/target/devo7e-256/target_defs.h
- src/target/ir8m/target_defs.h
- src/target/t8sg/target_defs.h
- src/target/t8sg_v2/target_defs.h
- src/target/t8sg_v2_plus/target_defs.h
The freq scanner is ported over to 128x64 screen Tx including devo10/devo12e/t8sg/devo7e-256.
> Add Scanner support to 128x64x1 screen

- src/Makefile
- src/fs/320x240x1/media/config.ini
- src/target/at9/Makefile.inc
- src/target/emu_at9/Makefile.inc
- utils/font/bdf_to_font.pl
Based on the change of generate ascii font file, we can pack 15normal.fon into the 64KB SPI flash on AT9. So switch it to 15p as default which is much more readable.
> Change the default font size on AT9 to 15p

- src/pages/128x64x1/pages.c
- src/pages/320x240x16/pages.c
This make logic explicit and in the same it saves 16 bytes ROM.
> Check PageID instead Page.init

- src/mixer.c
- src/mixer.h
This patch saves 248bytes of RAM, 124 bytes of rom.
I am not currently setup to actually test this so I'd appreciate it if someone could double check it.
> Convert mixer beep_lock and voice_lock variables to flags.

- src/protocol/protocol.c
1. Simplify the load logic to read .mod file
2. Fix error handling
3. Make sure we switch back font before we disable dialog.
4. Save about 50 bytes ROM.
> optimize module load code

- .travis.yml
- utils/archive_build_size.py
This will preserve image size for each build and annotate it (along with deltas) onto pull requests
> Store build image size (ram/rom) in GitHub status

- src/mixer.c
- src/mixer.h
- src/pages/common/_trim_page.c
The trim code is basically broken for many cases.
It is supposed to work as follows:
```
trim step moves in 0.1% increments from 0% to 10%
trim step moves in 1% increments from 10% to 100%
trim value has a maximum range of -100% to 100% and is independent of the step.  It should move 1% for a short-press of the trim button and 10% for a long-press of the trim button
the channel value should be adjusted based on trim-step * trim-value
```
The current code does not calculate the channel-adjustment properly with trim-step > 1% and does not consistently update the step-size with trim-step > 1%
This patch affects how trims are calculated and so could theoretically break models, but the trims were basically unusable in the range that the patch fixes anyway.
> Fix trim calculation

- src/config/model.c
- src/tests/test_model.c
also mark some functions as static to enable more opportunities for compiler to optimize.
> Add model test cases

- src/mixer.c
- src/tests/test_mixer.c
For some reason we were calling MIXER_CreateCyclicOutput() for each cyclic channel even though it does the full caclulation each time it is called.
> Only run cyclic calculation once.  Add several mixer tests

- src/target/at9/at9.ld
- src/target/common/devo/Makefile.inc
- src/target/devo10/Makefile.inc
- src/target/devo12/Makefile.inc
- src/target/devo7e-256/Makefile.inc
- src/target/devo7e/Makefile.inc
- src/target/devo8/Makefile.inc
- src/target/devof12e-XMS/Makefile.inc
- src/target/devof12e/Makefile.inc
- src/target/devof4-XMS/Makefile.inc
- src/target/devof4/Makefile.inc
- src/target/devof7-XMS/Makefile.inc
- src/target/devof7/Makefile.inc
- src/target/ir8m/Makefile.inc
- src/target/t8sg/Makefile.inc
- src/target/t8sg_v2/Makefile.inc
- src/target/t8sg_v2_plus/Makefile.inc
- utils/repack_ld.pl
For most targets, no need to have seperate _opt.ld now. Enhence Makefile to use original ld file.
at9 crc offset set to 0x150 right after vector table to avoid padding.
> Enable optimized link for all devo targets

- src/common.h
- src/datalog.c
- src/protocol/protocol.c
- src/screen/320x240x16/lcd_string.c
- src/screen/text/lcd_string.c
- src/target/common/devo/common_devo.h
- src/target/common/emu/common_emu.h
- src/target/common/filesystems/enable_devofs.h
- src/target/common/filesystems/enable_petit_fat.h
- src/target/devof12e/lcd.h
- src/target/devof7/lcd.h
In new compiler, strict-alias is assumed to have better optimization. The current implementation to use an array to simulate the struct FATFS breaks this assumption and cause gcc 8.2 generate wrong code. Fix it via using the exact type.
> Fix strict-alias of type FAT

- src/protocol/protocol.c
Run mixer calculations on timer after de-initializing protocol.  Ensures channel data is updated for functions like calibration.  Fixes #574 .
> Fix calibration (issue #574)

- src/mixer.c
- src/tests/test_mixer.c
Add tests for mixer dependency ordering and loop handling.
Fix code to properly reorder mixers and handle loops
> Fix mixer reordering and loop handling.  Fixes #580

- .travis.yml
Some small changes to travis.yml to speed up builds a little:
1. git clone only shallow
2. omit apt-get update
3. git needs no update through apt
4. move away from docker container to trusty VM, as docker containers are phased out anyways by travis
5. set minimal language, as we only need a very basic environment
> Speedup travis builds

- src/config/model.c
- src/config/model.h
- src/inputs.c
- src/mixer.h
This makes sure the variables are only in ROM not in RAM.
> Use the array type for strings

- src/config/display.h
Move it to bottom to avoid unalign other u16 members.
> Font is always u8

- src/datalog.h
- src/main.c
Set a flag to let the _getstandard runs after video is enabled in 3 seconds.
> Don't run video_setstandard in every event loop

- src/main.c
- src/target/common/emu/fltk.cpp
Use the PWR_Sleep to call the timer route every 100ms. Since PWR_Sleep is noon on ARM platform. This change should be a noop for real TX.
The event loop on a modern PC is fast enough and timer route still has reasonable accuracy.
This removes platform dependent code and make my debug life much easier as emu become a single thread application.
> Make emulator single thread

- src/config/language.c
We probably need to be managing this on a per-tx basis, though it is hard to set precisely due to the chicken-egg issue of needing to build before we know how many strings are needed
Alternatively, we shold probably look at the string list and see if any can be pruned out
> Increase translated string count so devo12 can build again

- .travis.yml
Upgrade the compiler to latest arm-none-eabi-gcc from ARM. The current compiler is too old to get any support. The new compiler gives better warnings and potentially leverage some new optimization technology.
> Update to GCC-8-2018-q4-major

- src/config/language.c
- src/tests/test_language.c
- utils/extract_strings.pl
Leave the code as it is but disable it from build. The new format prevent user to modify the translation file directly. Introduce the new format when we really need it later.
> Revert langv2

- src/config/tx.c
- src/config/tx.h
- src/pages/320x240x16/rtc_config.c
- src/rtc.c
No reason to combine the flags. The memory save is zero but the ROM waste is noticeable. This also make the tx configuration code hard to convert to data driven mode.
>  Move rtcflags into time and date format variables

- .travis.yml
- utils/clean_transifex_merge.py
- utils/extract_strings.pl
- utils/get_altered_languages.py
- utils/needs_nightly_rebuild.py
Similar functionality to deviation-manual.  When a nightly build is triggered:
* rebuild strings
* upload strings to transifex (only if there are non-comment changes)
* download strings from transifex
* remove any comment-only changes
* push changes to github
* don't re-trigger build on pushed translation changes
> Enable nightlies to upload/download from transifex and push to github.

- .travis.yml
After compiler upgrade, the new GCC is a 64bit application instead of a 32bit like GCC 4.8. Remove the package libc6-i386.
> No need install libc-i386

- src/gui/gui.c
This function should not ever be callable on a non-touch scrollbar since scrollbars are display only.
Should save ~120 bytes on non-touch transmitters
> Don't call GUI_TouchScrollbar() on non-touch transmitters

- .travis.yml
The upload coverage data is broken in my private CI runs as I didn't enable coveralls. Ignore the return code of coveralls cmd to workaround this.
> Ignore return code of upload coverage data

- src/pages/common/advanced/_mixer_page.c
- src/tests/test_pages_advanced_mixer.c
This patch re-implements the page-reordering algorithm.
It trades of code-size and performance for reduced stack usage.
Original stack usage for reorder_return_cb was 5248 bytes
There are 3 parts:
eda187fe : breaks up the function into 2 parts, making testing easier.  this increases code size by 36 bytes and reduces worst-case stack usage to 2120
8a18b0d : re-implements the mixer-shuffle portion of the code.  This one increases code size by an additional 32 bytes (78 total), and reduces worst-case stack usage to 652
1b4aed00 : re-implements the limit and template shuffling.  This one increase code size further by  104 bytes (182 total) and reduces worst-case stack usage to 120
I don't really understand the massive stack usage drop in the 1st commit.  All that it does is break one function …
> Reduce stack usage of page-reordering

- ChangeLog.md
- src/protocol/devo_cyrf6936.c
Change telemetry protocol option to support both standard (Devo) and QR-X350 telemetry formats.  The X350 sends lat/long as decimal degrees.  Standard format is degrees decimal minutes.
Fixes #627.
> Add special Devo telemetry format

- src/protocol/devo_cyrf6936.c
handle PROTOCMD_SETOPTIONS in the right way to avoid calling back to PROTOCOL_INIT. This can result a recursive call which we should avoid. And PROTOCOL_INIT is not supposed to expose to protocol anyway.
> Devo prototocol cleanup

- src/pages/128x64x1/debuglog_page.c
- src/pages/128x64x1/main_page.c
- src/pages/128x64x1/model_page.c
- src/pages/128x64x1/standard/common_standard.c
- src/pages/128x64x1/standard/curves_page.c
- src/pages/128x64x1/standard/drexp_page.c
- src/pages/128x64x1/standard/gyrosense_page.c
- src/pages/128x64x1/standard/swash_page.c
- src/pages/128x64x1/standard/switchassign_page.c
- src/pages/128x64x1/standard/throhold_page.c
- src/pages/128x64x1/standard/traveladj_page.c
- src/pages/128x64x1/telemconfig_page.c
- src/pages/128x64x1/telemtest_page.c
- src/pages/128x64x1/tx_configure.c
- src/pages/128x64x1/voiceconfig_page.c
- src/pages/320x240x16/main_page.c
- src/pages/320x240x16/model_page.c
- src/pages/320x240x16/pages.c
- src/pages/320x240x16/rtc_config.c
- src/pages/320x240x16/telemconfig_page.c
- src/pages/320x240x16/telemtest_page.c
- src/pages/320x240x16/tx_configure.c
- src/pages/320x240x16/voiceconfig_page.c
- src/pages/common/_menus.c
- src/pages/common/_model_page.c
- src/pages/common/_range_page.c
- src/pages/common/_scanner_page.c
- src/pages/common/_usb_page.c
After commit b7e1da19 if the model name or fixed id submenus are used the model config page can no longer be exited with EXT and ENT doesn't work to enter protocol options.  Seems like the modal flag is used to keep track of being in these submenus.
> Fix modal tracking bug introduced in PR #543

- src/target/devof12e/lcd.c
the range from 0x300 - 0x350 is reserved for icons.
> Fix regression on toggle icon on f12e-XMS

- src/mixer.c
- src/tests/test_mixer.c
The CalcChannels test was not properly initializing all its needed inputs
Also, remove static variable for MIXER_CalcChannels as it cannot be controlled via tests
> Fix TestCalcChannels to be order independent

- .travis.yml
Nightlies need to trigger a full build to calculate ROM sizes and to validate string lengths
Also re-enable pushing english updates to transifex.  I don't know why I commented that out
> Nightlies should trigger a full build

- src/misc.c
- src/pages/common/_usb_page.c
- src/target.h
- src/target/at9/at9_stubs.c
- src/target/common/devo/hid/hid_devo.c
- src/target/common/devo/msc2/usb_devo8.c
- src/target/common/emu/stubs.c
- src/target/test/test_stubs.c
- src/target/x9d/x9d_stubs.c
1. Split out USB_Enable from [MSC|HID]_Enable
2. Remove some duplicate code
3. remove the array EpInt_IN/OUT.
> Cleanup USB stack to save some ROM

- src/Makefile
This make postmortem of error.txt easier.
> Always generate debug symbols

- src/Makefile
If $LANGUAGE is set in the env, then devofs filesystems get language files even when they sholdn't.  LANGUAGE should not be inherited
> Don't inherit LANGUAGE from environmant

- src/config/model.c
- src/pages/common/_model_page.c
These bugs came in with the recent power setting changes.  Found problem in emulator.  Seemed to have no effect in devo10 or t8sg+.
> Fix index out-of-bounds and null pointer in power settings

- src/target/tx/devo/devof12e-XMS/Makefile.inc
devof12e-xms build broken due to missing 'else'
> Fix devof12e-XMS build

- src/Makefile
- utils/run_linter.py
This is not great for running 'zips' as it runs for each target as opposed to only once.  Not sure of a good way to fix that.
> Run lint (in non-failure mode) after every make

- src/target/drivers/mcu/stm32/adc.c
On Devo12, the ADC DMA is not properly enabled due to a typo.  This works on other radios because the same DMA is used for UART which enables the RCC for us.  the Devo12 has a different DMA for analog inputs, and so wasn't powered on properly.
> Enable correct DMA for ADC  Fix for #711 on Devo12

- src/protocol/bugs3_a7105.c
Addresses issue #738.  Telemetry packets continue to work with this change tested with a Bugs3 flight controller.
> Adjust post-transmit timing to eliminate wait loop

- src/protocol/spi/avr_program.c
- src/protocol/spi/cyrf6936.c
- src/target/drivers/display/8080/320x240x16.c
- src/target/drivers/display/i2c/video_tw8816.c
- src/target/drivers/display/spi/128x64x1_oled_ssd1306.c
- src/target/drivers/display/spi/video_ia9211.c
- src/target/drivers/input/rotary/rotary.c
- src/target/drivers/input/rotary/rotary_isr.c
- src/target/drivers/mcu/emu/protospi.h
- src/target/drivers/mcu/stm32/exti.h
- src/target/drivers/mcu/stm32/f1/nvic.h
- src/target/drivers/mcu/stm32/f1/pwr.h
- src/target/drivers/mcu/stm32/f1/rcc.h
- src/target/drivers/mcu/stm32/pwr.h
- src/target/drivers/mcu/stm32/spi_flash.c
- src/target/tx/devo/common/haptic.c
- src/target/tx/devo/common/hardware.h
- src/target/tx/devo/common/msc2/usb_devo8.c
- src/target/tx/devo/common/ports.h
- src/target/tx/devo/common/power.c
- src/target/tx/devo/common/ppmin.c
- src/target/tx/devo/common/protospi.h
- src/target/tx/devo/devo12/devo12_ports.h
- src/target/tx/devo/devo12/hardware.h
- src/target/tx/devo/devof12e/hardware.h
- src/target/tx/radiolink/common/common_at.h
- src/target/tx/radiolink/common/hardware.h
Replace all hardcoded GPIO pins with those defined in hardware.h
> STM32 reorg: remove hardcoded gpio pin definitions

- src/pages/320x240x16/standard/standard.h
because this variable is defined here:
struct advmixer_obj {
guiButton_t testico;
guiButton_t reorderico;
union {
guiButton_t but;
guiLabel_t lbl;
} name[ENTRIES_PER_PAGE];
guiButton_t tmpl[ENTRIES_PER_PAGE];
guiLabel_t src[ENTRIES_PER_PAGE];
guiLabel_t sw1[ENTRIES_PER_PAGE];
guiLabel_t sw2[ENTRIES_PER_PAGE];
guiKeyboard_t keyboard;
guiScrollable_t scrollable;
};
> Fix crash on at10

- src/target/drivers/input/analog/analog.c
- src/target/drivers/mcu/stm32/gpio.h
- src/target/tx/devo/common/devo.h
- src/target/tx/devo/common/power.c
- src/target/tx/devo/devo10/channels.c
- src/target/tx/devo/devo12/channels.c
- src/target/tx/radiolink/at10/at10_power.c
- src/target/tx/radiolink/at9/at9_power.c
This should fix the crashes in transmitters other than the devo12 due to the recent ADC updates.
> Fix crash introduced by #750

- utils/extract_strings.pl
We can safely ignore the line start with "Contents of".
> Fix warnings on osx build

- src/protocol/ppmout.c
- src/target.h
- src/target/drivers/mcu/emu/radio.c
- src/target/tx/devo/common/protocol/pwm.c
- src/target/tx/opentx/x9d/x9d_stubs.c
- src/target/tx/other/test/radio.c
- src/target/tx/radiolink/common/at_stubs.c
Add an option to reverse signal polarity to the PPM protocol.
~~Note that PPM out is broken in current master (at least on T8SG V2+), it outputs only 1 pulse per frame, maybe a DMA issue ?~~ (fixed by #777 )
Tested with an older version.
> Add inverted ppmout option

- src/protocol/spi/nrf24l01.c
- src/target/drivers/mcu/emu/protospi.h
- src/target/tx/devo/common/protospi.h
- src/target/tx/opentx/x9d/protospi.h
- src/target/tx/other/test/protospi.h
- src/target/tx/radiolink/common/protospi.h
- src/universaltx/include/protospi.h
Fix rare nrf24l01 problem where CS goes HIGH before the last clock pulse has completed:
When this happens, the last byte is not registered by the nrf24l01 and is replaced by the previous one.
> Fix rare nrf24l01 problem

- src/protocol/bayang_nrf24l01.c
This change to the Bayang protocol adds an option to steal two presently unused (by the Silverware firmware, which targets several Bayang quads) in the protocol to send two more "analog" (non-binary) channels of data to the Rx. With corresponding changes on the Rx firmware, those new aux channels can be used to do more interesting things than the other binary aux channels. Some users have really liked PID tuning with the extra channels.
More information on the Silverware additions here:
https://www.rcgroups.com/forums/showthread.php?3121896-Analog-Aux-Channels-for-Silverware
The main NFE Silverware fork now has this feature available:
https://github.com/NotFastEnuf/NFE_Silverware
I am making a corresponding pull request to DIY Multiprotocol TX with the same additions to the Bayang …
> Add Silverware's analog aux channel feature to Bayang protocol

- src/config/model.c
- src/curves.c
- src/datalog.c
- src/inputs.c
- src/mixer.c
- src/mixer_standard.c
- src/pages/128x64x1/main_config.c
- src/pages/128x64x1/trim_page.c
- src/pages/320x240x16/model_page.c
- src/pages/320x240x16/trim_page.c
- src/pages/common/_chantest_page.c
- src/pages/common/_datalog_page.c
- src/pages/common/_main_config.c
- src/pages/common/_model_config.c
- src/pages/common/_model_page.c
- src/pages/common/_trim_page.c
- src/pages/common/advanced/_mixer_curves.c
- src/pages/common/advanced/_mixer_page.c
- src/pages/common/advanced/_mixer_setup.c
- src/rtc.c
- src/rtc.h
Make most _tr calls only happen inside pages with the following exceptions:
1. input.c
2. telemetry
which will be addressed separately.
> Cleanup _tr usage

- src/target/drivers/filesystems/devofs/buildfs.py
If using a python3 venv, buildfs.py will try to run in python3 and fail.
Script needs to be updated to python3 but that will take more time.
> Force buildgs to use python2 until the script is converted to python3

- src/protocol/frsky_s_telem._c
- src/protocol/frskyx_cc2500.c
Fixes issue with interpreting corrupted telemetry packets as valid data.
> Add CRC check for s.port telemetry

- src/target/drivers/display/spi/128x64x1.c
Code refactoring missed a constant change that affected SPI clock speed to display.
> Fix oled display problem where display remained dark

- src/protocol/mjxq_nrf24l01.c
Add "Phoenix" format option to the MJXq protocol.
Channel 5: arm
This is a clone of the EAchine E010 with altitude hold, same as the E010 protocol it's using XN297L @ 250 kbps and doesn't work well with every nrf24l01 modules.
https://www.deviationtx.com/forum/protocol-development/8314-tdr-phoenix-mini-eachine-e010-clone
I'd like to add a note in the manual/wiki for those XN297L @ 250 kbps (sub)protocols, but I'm not sure how to phrase it without being too technical. To make it short, the xn297(L) has a ~+200 kHz frequency drift compared to the nrf24l01, that's not an issue @ 1 Mbps but with 250 kbps the xn297l has a tighter oscillator accuracy requirement (20ppm vs 60ppm) thus not enough selectivity to cope with this drift sometimes. Success depends only on the (in)accuracy of the …
> Protocol for TDR Phoenix Mini

- src/target/drivers/input/addon_switch/addon_btnmatrix.c
Button mask wasn't computed properly when extra-switches were enabled.  As reported in #838
> Fix broken trim due to addon-switches

- src/protocol/frsky_s_telem._c
- src/protocol/frskyx_cc2500.c
- src/protocol/pxxout.c
When I added the s.port CRC check for serial s.port the test was also applied to FrskyX s.port telemetry, which does not have the CRC.  This PR fixes the problem by only checking CRC for s.port telemetry received on the serial port (i.e. for the PXX protocol).
Relevant [forum thread](https://www.deviationtx.com/forum/6-general-discussions/8431-jumper-t8s-v2-plus-frsky-smartport-telemetry).
> Fix FrskyX s.port telemetry

- src/protocol/bayang_nrf24l01.c
For SilverWare, optional telemetry support was added to the Bayang protocol quite some time ago.
Recently, current PID settings were added to the telemetry data. This pull request makes them available via FadesA, FadesB, and FadesR. The change is backwards compatible and has no implications for older firmware which does not send these values.
The PID values are sent sequentially using just two bytes.
Details: https://www.rcgroups.com/forums/showpost.php?p=42032515&postcount=398
> Read multiplexed PID values from telemetry data.

- src/protocol/e016h_nrf24l01.c
- src/protocol/h8_3d_nrf24l01.c
- src/protocol/hisky_nrf24l01.c
- src/protocol/hitec_cc2500.c
- src/protocol/hm830_nrf24l01.c
- src/protocol/hontai_nrf24l01.c
- src/protocol/hubsan_a7105.c
- src/protocol/inav_nrf24l01.c
- src/protocol/j6pro_cyrf6936.c
- src/protocol/joysway_a7105.c
- src/protocol/kn_nrf24l01.c
- src/protocol/loli_nrf24l01.c
- src/protocol/mjxq_nrf24l01.c
- src/protocol/mt99xx_nrf24l01.c
- src/protocol/ncc1701_nrf24l01.c
- src/protocol/ne260_nrf24l01.c
- src/protocol/ppmout.c
- src/protocol/scanner_cyrf6936.c
- src/protocol/spi/a7105.c
- src/protocol/spi/cc2500.c
- src/protocol/spi/nrf24l01.c
- src/target/tx/devo/common/protocol/pwm.c
- src/target/tx/devo/devof7/protocol.ld
In master several of the .mod files for the devo F series are four byte files.  The loader file change in PR #770 were not made in the devof7 file.  With this change the conditional define of PROTO_Cmds can be removed from protocol files, but the protocol command function name must now match /*_Cmds/.
Only some protocol files were changed by #770.  This PR removes the rest of the unnecessary defines.  
A remaining issue is the scancyrf.mod and xn297dump.mod files.  These are both 4 byte files in the devo7e build, but only the scancyrf.mod file is 4 bytes long in the devof* builds.
> Fix devo F series builds

- src/protocol/Makefile.inc
the redpine.mod seems to be missing from the devo7e build. this pull requests adds the according entries to the Makefile
> add missing redpine protocol module

- src/pages/common/_crsfdevice_page.c
Just a very small fix of the CRSF config page when showing int16 and uint16 data types.
> fix crsf datatype for config page

- src/crsf.h
- src/protocol/crsf_uart.c
Implementation is based on opentx, tested with ExpressLRS hardware.
Before - packet rate is stuck at 250 packets per second.
After - packet rate depends on the settings and varies from 25 to 500 per second.
Tested with T8SG V2 plus, builds for T8SG V2 and T8SG V2 plus attached below.
[deviation-t8sg_v2_plus-v5.0.0-f04bc27.zip](https://github.com/DeviationTX/deviation/files/7532297/deviation-t8sg_v2_plus-v5.0.0-f04bc27.zip)
[deviation-t8sg_v2-v5.0.0-f04bc27.zip](https://github.com/DeviationTX/deviation/files/7532298/deviation-t8sg_v2-v5.0.0-f04bc27.zip)
> Added crsf-shot

- src/telemetry.c
- src/telemetry/telem_crsf.c
Increase CRSF voltage telemetry alarm limit to 50 volts.
Increase CRSF current telemetry alarm limit to 100 amps.
Fix voice announcement of voltage and current.  Was off by factor of 10.
Tested by mooiweertje on deviationtx.com
> Adjust crsf telem limits and voice scaling

- src/crsf.h
- src/pages/128x64x1/crsfconfig_page.c
- src/pages/128x64x1/crsfdevice_page.c
- src/pages/320x240x16/crsfconfig_page.c
- src/pages/common/_crsfconfig_page.c
- src/pages/common/_crsfdevice_page.c
- src/pages/common/crsfconfig_page.h
- src/protocol/crsf_uart.c
- src/target/drivers/serial/uart/uart.c
- src/target/drivers/serial/uart/uart_isr.c
Names of max length (16 including nul) or greater caused incorrect calculation of location of next parameter in receiver buffer.
Fixes issue in serial sending code where link was switched from tx to rx before last byte finished sending.
Fixes updating CRSF config page device list when new info message received from new device.
> Fix incorrect handling of long names

- src/protocol/crsf_uart.c
Incorrect value was shown due to incorrect conversion.  Telemetry data is in fixed point degrees * 10,000,000.  Internal representation is seconds *1000.
> Fix incorrect CRSF GPS latitude and longitude display

- src/protocol/crsf_uart.c
Sends model id of 0 to ELRS if the Deviation Fixed ID is greater than 63.   When sending a model id to the TX it should always be in the range 0-63.
> Limit range of fixed id in CRSF protocol

- src/config/model.c
- src/protocol/radiolink_cc2500.c
- src/target/drivers/mcu/emu/stubs.c
Allows hex notation and large positive numbers for model configuration file numbers.
> Allow hex notation for fixed_id

- src/pages/128x64x1/dialogs.c
- src/pages/128x64x1/pages.h
- src/pages/320x240x16/dialogs.c
- src/pages/320x240x16/pages.h
- src/pages/common/_crsfdevice_page.c
- src/pages/common/_dialogs.c
Dialog type may change after creation, for example from PROGRESS to CONFIRMATION_NEEDED.  This requires changing the dialog from one button to two buttons.
Also handle longer COMMAND info strings - up to 39 characters.
> Add handling for changes in CRSF COMMAND dialogs

- src/pages/common/_crsfdevice_page.c
If number selection step is not defined, then set step to 1. Fixes an issue with not being able to change VTX channel over the radio. VTX channel is an uint8 in ELRS version 3.4.0+
> Set default value for number selection step value in _crsfdevice_page.c

- src/crsf.h
- src/pages/128x64x1/crsfdevice_page.c
- src/pages/320x240x16/crsfdevice_page.c
- src/pages/common/_crsfdevice_page.c
- src/protocol/crsf_uart.c
Fix bugs and improve usability in handling CRSF parameter menus.
1. When a parameter is changed, all elements of the current folder and the folder itself are reloaded.  This handles dynamic changes to parameter names and options caused by changes to other parameters.  For example, with ELRS changing the packet rate can cause the available switch mode options to change.  This can be a little slow at 400Kbps data rate so be sure to use 1.87Mbps(ELRS) or 2.00Mbps(TBS).
2. Parameters where the label + value lengths are wider than the screen are split into two rows.  This fixes an issue with values partially overwriting label strings in the display.
3. When navigating between folders the current selection in a folder is remembered.  If the folder is opened again the same row will be selected. …
> CRSF configuration menu handling update

- src/crsf.h
- src/pages/128x64x1/crsfdevice_page.c
- src/pages/common/_crsfconfig_page.c
- src/pages/common/_crsfdevice_page.c
- src/protocol/crsf_uart.c
- hidden flag was not set correctly
- TBS param echo caused page update problem
- Fix overlap by a few pixels
- Add Show Hidden protocol option to display CRSF config parameters even when they're marked hidden.
The only place I know hidden parameters are used is in the TBS Radio Settings folder.  Setting the Region to anything but Open changes the Region and Frequency parameters to hidden.  The Multi-Bind option is hidden unless the tx is registered with TBS.
The Show Hidden option can be used to change the Region even if was previously changed to something other than Open.  Changing the Multi-Bind option has no effect - the display will change back to Disabled after the change is sent to the tx.  It can only be Enabled if the tx is registered.  Changes to the Frequency when the Region is …
> Crsf hidden parameter fix

- src/protocol/hontai_nrf24l01.c
The HonTai protocol has a new format option XKK170.
Channels 1-4 are AETR respectively.
Channel 5 is gyro calibration. This is a "momentary" switch.  Set value greater than zero to initiate calibration, then back to less than zero.
Channel 6 is takeoff/landing. Also momentary.
Channel 7 is emergency. Also momentary.
Deviation doesn't implement rate selection in these protocols. The rate is fixed at high and the mixers should be used to tone down the flight controls as needed.  The protocol aileron and elevator trim channels are used to extend control throw.  Use deviation trims to get level flight with controls at neutral.
> Update HonTai protocol with format to support WlToys XKK170 heli
